[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  external_node_modules = ["@prisma/client", "bcrypt", "express", "swagger-ui-dist", "swagger-ui-express"]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
